baseURL: https://kevfan.github.io/
languageCode: en-us
title: Kevin Fan
theme: "PaperMod"
publishDir: "docs"

params:
  homeInfoParams:
    Content: Welcome! This is just a place for me to share some tech blogs that I believe might be helpful for others.
    
  socialIcons:
    - name: github
      url: "https://github.com/KevFan"
    - name: linkedin
      url: "https://www.linkedin.com/in/kevfan/"
  
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowShareButtons: true